version: "3"

services:

  mongodb:
    image: mongo:4.4.15
    platform: linux/amd64
    volumes: 
      - /data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
    ports:
      - 27417:27017

  api:
    build:
      context: ./
      dockerfile: ./api/Dockerfile
      target: base
      args:
        UID: ${UID}
        GID: ${GID}
    user: $UID:$GID
    volumes:
      - ./api:/app/api
      - /app/api/node_modules
      - ./shared:/app/api/shared
      - .env.dev:/app/.env
      - ./volumes:/app/volumes
    depends_on:
      mongodb:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8082/health"]
    working_dir: /app/api
    ports:
      - 8082:8082

  handler:
    build: 
      context: ./
      dockerfile: ./handler/Dockerfile
      target: base
      args:
        UID: ${UID}
        GID: ${GID}
    platform: linux/amd64
    volumes:
      - ./handler:/app/handler
      - /app/handler/node_modules
      - ./shared:/app/handler/shared
      - .env.dev:/app/.env
      - ./volumes:/app/volumes
    depends_on:
      mongodb:
        condition: service_healthy
    tty:
        true # for bids-validator color output

  ui:
    build: ./ui
    platform: linux/amd64
    volumes:
      - ./ui:/ui
      - ./shared:/app/ui/shared
      - /ui/node_modules
    environment:
      VITE_APIHOST: http://localhost:8082
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:3000"]
    ports:
      - 3000:3000
