version: "2.0"

instances:
    # mongodb: # ORIGINAL
    #     container_name: brainlife_ezbids-mongodb
    #     image: docker://mongo:4.4.15
    #     platform: linux/amd64
    #     volumes:
    #         - /tmp:/tmp
    #     # healthcheck:
    #     #     test: echo 'db.runCommand("ping").ok' | mongo localhost:27017/test --quiet
    #     #     interval: 10s
    #     #     timeout: 10s
    #     #     retries: 5
    #     ports:
    #         - 27417:27017 #for local debugging
    #     post:
    #         command:
    #             - "mongod --dbpath /tmp"
    #         # command: ["mongod --dbpath /tmp"]

    # mongodb:  # NEW BUT STILL BAD
    #     container_name: brainlife_ezbids-mongodb
    #     build:
    #         context: ./mongodb
    #         options:
    #             - fakeroot
    #     platform: linux/amd64
    #     # volumes:
    #     #     - ./data/db:/data/db
    #     post:
    #         command: [ "/bin/bash", "./mongodb/mongodb_setup.sh"]
    #     ports:
    #         - 27417:27017 #for local debugging

    # mongodb:  # THIRD ATTEMPT
    #     container_name: brainlife_ezbids-mongodb
    #     image: docker://mongo:4.4.15
    #     platform: linux/amd64
    #     volumes:
    #         - ./data/db:/data/db
    #     ports:
    #         - 27417:27017 #for local debugging
    #     # run:
    #     #     background: true # Does this actually run things in the background


    # api:
    #     container_name: brainlife_ezbids-api
    #     build:
    #       context: .
    #       options:
    #         - fakeroot
    #     platform: linux/amd64
    #     volumes:
    #         - ./api:/app/api
    #         - /tmp:/tmp
    #     # depends_on:
    #     #     mongodb:
    #     #         condition: service_healthy
    #     post:
    #         command: ["/bin/bash", "./dev.sh"] # This seems to cause the npm install to freeze
    #     ports:
    #         - 8082:8082 #localhost runs on local browser to it needs to access api via host port

    # handler:
    #     container_name: brainlife_ezbids-handler
    #     build:
    #       context: ./handler
    #       options:
    #         - fakeroot
    #     platform: linux/amd64
    #     volumes:
    #         - .:/app
    #         - /tmp:/tmp
    #     depends_on:
    #         mongodb:
    #             condition: service_healthy
    #         api:
    #             condition: service_healthy
    #     environment:
    #         MONGO_CONNECTION_STRING: mongodb://mongodb:27017/ezbids
    #     tty: true #turn on color for bids-validator output
    #     command: pm2 start handler.js --attach --watch --ignore-watch "ui **/node_modules"

    # ui:
    #     container_name: brainlife_ezbids-ui
    #     build:
    #       context: ./ui
    #       options:
    #         - fakeroot
    #     platform: linux/amd64
    #     volumes:
    #         - ./ui/src:/ui/src #don't copy node_modules which might be compiled for mac (vite won't work)
    #     environment:
    #         VITE_APIHOST: http://localhost:8082
    #     # healthcheck:
    #     #     test: ["CMD", "curl", "-f", "http://localhost:3000"]
    #     ports:
    #         - 3000:3000 #vite wants to be exposed on the host for HMR?